name: Server CI

on:
  pull_request:
    branches: [ main, master ]
    paths:
      - 'server/**'
      - '.github/workflows/server-ci.yml'
  push:
    branches: [ main, master ]
    paths:
      - 'server/**'
      - '.github/workflows/server-ci.yml'

jobs:
  build-and-test:
    name: Build and Test Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        working-directory: server
        run: npm test

      - name: Build server
        working-directory: server
        run: npm run build
